-- MySQL Workbench Synchronization
-- Generated: 2019-12-09 17:29
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: argenis

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `pokemon` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `pokemon`.`Trainer` (
  `idTrainer` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idTrainer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `pokemon`.`Pokedex` (
  `idPokemon` INT(11) NOT NULL,
  `idTrainer` INT(11) NOT NULL,
  CONSTRAINT `fk_Pokedex_Trainer`
    FOREIGN KEY (`idTrainer`)
    REFERENCES `pokemon`.`Trainer` (`idTrainer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
